#
#   Copyright (C) 2021-2022 ABZ Conference <https://abz-conf.org>
#   All rights reserved.
#
#   Developed by: Philipp Paulweber et al.
#                 <https://github.com/abz-conf/abz-conf.github.io/graphs/contributors>
#
#   This file is part of abz-conf.github.io.
#
#   abz-conf.github.io is licensed under a
#   Creative Commons Attribution 4.0 International License.
#
#   You should have received a copy of the license along with this
#   work. If not, see <http://creativecommons.org/licenses/by/4.0/>.
#

# https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments

name: github-pages

on:
  push:
    branches-ignore:
      - 'push-action/**'


jobs:
  github-pages:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_extended_0.83.1_Linux-64bit.tar.gz
        sudo mv hugo_extended_0.83.1_Linux-64bit.tar.gz /usr/bin/
        (cd /usr/bin; sudo tar xvf hugo_extended_0.83.1_Linux-64bit.tar.gz)
        hugo version
    - name: Build
      run: |
        make build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        make deploy
        git config --local user.email ${{ github.event.pusher.email }}
        git config --local user.name ${{ github.event.pusher.name }}
        git add .
        git commit -m "${{ github.event.head_commit.message }} [actions skip]"
    - name: Publish
      uses: CasperWA/push-protected@v2
      if: github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: master
